// DISPLAY
#define FPS 60
#define WIDTH 1280
#define HEIGHT 720

#define NUM_FONTS 1

// SPRITES
#define NUM_PATH 28
#define NUM_CRIAR_SPRITES 2
#define NUM_SPRITES_PLAYER 3
#define NUM_SPRITES_ENEMIE 2

// PLAYER
#define QNT_ACOES 5

// INIMIES
#define NUM_ENEMIES 5